import * as T from 'three';
import {GameAudio,type AudioSettings} from './audio';
import R from '@dimforge/rapier3d-compat';
import {surface,damp,turn} from './surfaces';
import {atmosphere,hills,roadsidePlanting,garden} from './landscape';
import {traveller} from './avatar';
import {animal,updateAnimals,type AmbientAnimal} from './animals';
import {furnishLot} from './architecture';
import {createRoadMeshes} from './roads';
import {visualShots,downloadEvidence,type VisualShot} from './visual-qa';
import {places,mission,type Point,type Save,newSave,advanceMission,purchase,validateSave} from './content';
import {type Road,distance,nearestRoad,route} from './navigation';
import {box,cyl,ball,mat,person,animatePerson,bike,car,gate,house,tree,boat,sign,label,batchStatic} from './models';

export type Snapshot={save:Save;speed:number;driving:string|null;prompt:string;near:string|null;location:string;fps:number;heading:number;time:string;route:Point[];position:Point;ready:boolean;saved:boolean};
type Vehicle={id:string;name:string;mesh:T.Group;body:R.RigidBody;collider:R.Collider;angle:number;speed:number;previous:T.Vector3;previousAngle:number;type:'bike'|'car'};
type Chunk={group:T.Group;center:Point;colliders:R.Collider[]};
export class Game {
 renderer:T.WebGLRenderer;scene=new T.Scene();camera=new T.PerspectiveCamera(58,1,.1,3500);world!:R.World;controller!:R.KinematicCharacterController;vcontroller!:R.KinematicCharacterController;
 player=traveller();body!:R.RigidBody;collider!:R.Collider;vehicles:Vehicle[]=[];chunks:Chunk[]=[];solids:T.Object3D[]=[];npcs:{id:string;mesh:T.Group;origin:Point}[]=[];roads:Road[]=[];
 save:Save=newSave();position:Point={x:-12,z:0};angle=Math.PI/2;vertical=0;keys=new Set<string>();stick={x:0,y:0};driving:Vehicle|null=null;paused=true;disposed=false;ready=false;
 animals:AmbientAnimal[]=[];qaMode=false;qaShot:VisualShot|null=null;
 velocity=new T.Vector2();visualPrevious=new T.Vector3(-12,.2,0);visualCurrent=new T.Vector3(-12,.2,0);previousAngle=Math.PI/2;motionSpeed=0;airborne=false;sky!:ReturnType<typeof atmosphere>;
 cameraYaw=Math.PI/2;pitch=.14;drag:{id:number;x:number;y:number}|null=null;accumulator=0;last=0;anim=0;lastEmit=0;frames=0;fps=60;near:string|null=null;route:Point[]=[];routeUpdated=0;targetId:string|null=null;
 ground!:T.Mesh;sea!:T.Mesh;bay!:T.Group;shop!:T.Group;marker!:T.Group;sun!:T.DirectionalLight;sunAngle=0;quality='balanced';raf=0;resizeObs:ResizeObserver;toast:(s:string)=>void;onPanel:(s:string)=>void;onState:(s:Snapshot)=>void;saved=false; audio=new GameAudio();lastChunk='';saveTimer=0;roadDisposer:T.BufferGeometry[]=[];
 constructor(public container:HTMLElement,onState:(s:Snapshot)=>void,onPanel:(s:string)=>void,toast:(s:string)=>void){
  this.onState=onState;this.onPanel=onPanel;this.toast=toast;
  this.renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.95;this.renderer.outputColorSpace=T.SRGBColorSpace;container.appendChild(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-label','Thế giới 3D Đông Hải');
  this.resizeObs=new ResizeObserver(()=>this.resize());this.resizeObs.observe(container);this.resize();
  window.addEventListener('keydown',this.keydown);window.addEventListener('keyup',this.keyup);window.addEventListener('blur',this.blur);document.addEventListener('visibilitychange',this.visibility);window.addEventListener('pagehide',this.persist);
  this.renderer.domElement.addEventListener('pointerdown',this.pointerDown);this.renderer.domElement.addEventListener('pointermove',this.pointerMove);this.renderer.domElement.addEventListener('pointerup',this.pointerUp);this.renderer.domElement.addEventListener('pointercancel',this.pointerUp);this.renderer.domElement.addEventListener('contextmenu',this.context);
 }
 async init(){
  await R.init();if(this.disposed)return;
  const response=await fetch('/data/roads.json');if(!response.ok)throw new Error('Không tải được dữ liệu đường.');this.roads=await response.json();if(this.disposed)return;
  this.world=new R.World({x:0,y:-18,z:0});this.world.timestep=1/60;this.controller=this.world.createCharacterController(.025);this.controller.enableAutostep(.35,.3,true);this.controller.enableSnapToGround(.3);this.controller.setMaxSlopeClimbAngle(.75);this.vcontroller=this.world.createCharacterController(.04);this.vcontroller.setSlideEnabled(true);
  this.scene.background=new T.Color('#9ac7d5');this.scene.fog=new T.FogExp2('#a6c6c4',.0013);this.scene.add(new T.HemisphereLight('#d1e5ef','#736f4e',1.25));this.sky=atmosphere(this.scene);this.sun=new T.DirectionalLight('#fff1c9',3.0);this.sun.position.set(-80,130,70);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1536,1536);Object.assign(this.sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45,near:1,far:350});this.sun.shadow.bias=-.0002;this.sun.shadow.normalBias=.045;this.scene.add(this.sun,this.sun.target);
  this.ground=box(this.scene,2200,.5,1500,740,-.3,-190,'#9b9f78');this.ground.material=surface('earth','#afa581');this.ground.castShadow=false;this.world.createCollider(R.ColliderDesc.cuboid(1100,.3,750).setTranslation(740,-.35,-190));
  this.createRoads();this.environment();this.createBuildings();this.createPOIs();roadsidePlanting(this.scene,this.roads);
  this.body=this.world.createRigidBody(R.RigidBodyDesc.kinematicPositionBased().setTranslation(-12,1,0));this.collider=this.world.createCollider(R.ColliderDesc.capsule(.52,.26),this.body);this.player.position.set(-12,.2,0);this.scene.add(this.player);
  this.addVehicle('bike','Xe máy • Đông Hải',{x:-5,z:2.7},Math.PI/2);this.addVehicle('car','Ô tô • Coastal',{x:-24,z:3},Math.PI/2);
  this.createAnimals();this.world.step();this.ready=true;this.camera.position.set(-19,4,1);this.camera.lookAt(-12,1.2,0);this.raf=requestAnimationFrame(this.loop);this.emit();
 }
 selectVisualShot(index:number){
  if(!this.ready||!this.qaMode)return;
  const shot=visualShots(this.roads)[index];if(!shot)return;
  this.qaShot=shot;this.changeQuality('high');this.changeTime(false);
  this.keys.clear();this.stick={x:0,y:0};this.drag=null;this.velocity.set(0,0);
  this.anim=0;this.accumulator=0;this.vertical=0;this.motionSpeed=0;this.airborne=false;
  this.position={...shot.anchor};this.angle=Math.PI/2;this.previousAngle=this.angle;this.cameraYaw=this.angle;
  const rotation={x:0,y:Math.sin(this.angle/2),z:0,w:Math.cos(this.angle/2)};
  for(const v of this.vehicles){
   const p=shot.bike&&v.type==='bike'?shot.anchor:v.type==='bike'?{x:-5,z:2.7}:{x:-24,z:3};
   const position={x:p.x,y:.65,z:p.z};
   v.body.setTranslation(position,true);v.body.setNextKinematicTranslation(position);
   v.body.setRotation(rotation,true);v.body.setNextKinematicRotation(rotation);
   v.angle=this.angle;v.previousAngle=this.angle;v.speed=0;
   v.mesh.userData.reset?.();v.mesh.position.set(p.x,.05,p.z);v.mesh.rotation.set(0,this.angle,0);v.previous.copy(v.mesh.position);
  }
  this.driving=shot.bike?this.vehicles[0]:null;
  const position={x:shot.anchor.x,y:1,z:shot.anchor.z};
  this.body.setTranslation(position,true);this.body.setNextKinematicTranslation(position);
  this.collider.setEnabled(!shot.bike);
  this.visualCurrent.set(position.x,shot.bike?-.02:.2,position.z);this.visualPrevious.copy(this.visualCurrent);
  this.player.position.copy(this.visualCurrent);this.player.rotation.set(0,this.angle,0);this.player.visible=true;
  this.player.userData.reset?.(shot.bike?'ride':'idle');
  this.world.step();this.lastChunk='';
  for(const c of this.chunks){const d=distance(this.position,c.center);c.group.visible=d<230;c.colliders.forEach(v=>v.setEnabled(d<100));}
  this.bay.position.set(-8,0,-2.4);for(const a of this.animals||[]){a.mesh.position.set(a.origin.x,0,a.origin.z);a.mesh.rotation.y=0;a.mesh.visible=distance(this.position,a.origin)<75;a.mesh.userData.update(0,false);}this.emit();
 }
 exportVisualEvidence(){if(!this.qaShot)return;downloadEvidence(this.qaShot.id+'-metrics.json',JSON.stringify({shot:this.qaShot,version:'0.4.0-asset-rebuild',quality:this.quality,viewport:{width:this.container.clientWidth,height:this.container.clientHeight,pixelRatio:this.renderer.getPixelRatio()},time:'09:30',camera:{position:this.camera.position.toArray(),quaternion:this.camera.quaternion.toArray(),fov:this.camera.fov},render:{...this.renderer.info.render},memory:{...this.renderer.info.memory},fps:null,performanceNote:'Frozen deterministic composition; FPS is not gameplay performance',visualScore:null},null,2));}
 capture(){if(!this.ready)return;this.renderer.render(this.scene,this.camera);this.renderer.domElement.toBlob(blob=>{if(!blob){this.toast('Không chụp được cảnh.');return;}const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=(this.qaShot?.id||'dong-hai-scene-'+Date.now())+'.png';link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);this.toast('Đã chụp cảnh 3D hiện tại.');},'image/png');}
 resize(){const w=this.container.clientWidth,h=this.container.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 createRoads(){const built=createRoadMeshes(this.roads);this.scene.add(built.group);for(const mesh of built.collision)this.world.createCollider(R.ColliderDesc.trimesh(mesh.vertices,mesh.indices));}
 environment(){
  // Original illustrative terrain and props; not reconstructed Google imagery.
  let seed=417;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
  hills(this.scene);
  this.sea=box(this.scene,1000,.15,1900,1906,.04,-220,'#519eaa');this.sea.material=surface('water','#3d8691');this.sea.castShadow=false;
  // Water gameplay boundary follows an explicit prototype envelope, not a measured shoreline.
  this.world.createCollider(R.ColliderDesc.cuboid(5,10,1000).setTranslation(1535,0,-200));
  for(let i=0;i<14;i++){const b=boat();b.position.set(1580+rand()*500,0,-650+rand()*900);b.rotation.y=rand()*6;this.scene.add(b);}
  for(let i=0;i<3;i++){const pond=new T.Mesh(new T.CircleGeometry(32+i*13,32),new T.MeshStandardMaterial({color:'#759893',roughness:.4}));pond.rotation.x=-Math.PI/2;pond.scale.set(1.3,.7,1);pond.position.set(-20+i*95,-.015,-75-i*22);this.scene.add(pond);}
  const foliage=new T.Group();for(let i=0;i<120;i++){const x=-100+rand()*1600,z=-580+rand()*800;const q=nearestRoad({x,z},this.roads);if(distance({x,z},q)<9||distance({x,z},places[4])<15)continue;const tr=tree(x>1270,i%4);tr.position.set(x,0,z);tr.scale.setScalar(.8+rand()*.65);foliage.add(tr);}this.scene.add(foliage);
  for(let i=0;i<26;i++){const road=this.roads[Math.floor(rand()*this.roads.length)];const p=road.points[Math.floor(rand()*road.points.length)];if(p.x<0||p.x>1460||p.z<-600||p.z>150)continue;const pole=cyl(this.scene,.1,.16,7,p.x+4,3.5,p.z+4,'#b0ada0',6);box(this.scene,1.1,.08,.08,p.x+4,6.7,p.z+4,'#5d6259');pole.castShadow=false;}

 }
 createBuildings(){
  const used:Point[]=[],palettes=['#d9ccb5','#d6d8be','#b5c5b9','#d2b8a4','#a6bcb5','#e0d6be'];let count=0;
  // Road-aligned illustrative infill: these are not surveyed building footprints.
  for(const road of this.roads)for(let i=1;i<road.points.length;i++){
   const a=road.points[i-1],b=road.points[i],length=distance(a,b);if(length<1)continue;const nx=-(b.z-a.z)/length,nz=(b.x-a.x)/length;
   for(let t=8;t<length;t+=19)for(const side of [-1,1]){
    const p={x:a.x+(b.x-a.x)*t/length,z:a.z+(b.z-a.z)*t/length};if(p.x<680||p.x>1450||p.z< -540||p.z>100||count>=105)continue;if(places.some(v=>distance(v,p)<22))continue;
    const setback=road.width/2+6.7;const q={x:p.x+nx*side*setback,z:p.z+nz*side*setback};if(used.some(v=>distance(v,q)<16)||distance(q,nearestRoad(q,this.roads))<8)continue;
    const w=6+count%3,d=7,h=count%4===0?6.6:3.9;const yaw=Math.atan2(p.x-q.x,p.z-q.z);
    const corners=[[-w/2,-d/2],[w/2,-d/2],[-w/2,d/2],[w/2,d/2]].map(([x,z])=>({x:q.x+Math.cos(yaw)*x+Math.sin(yaw)*z,z:q.z-Math.sin(yaw)*x+Math.cos(yaw)*z}));
    if(corners.some(c=>distance(c,nearestRoad(c,this.roads))<road.width/2+.5))continue;
    const g=house(w,d,h,palettes[count%palettes.length],false,count);garden(g,w,d,count);const lotColliders=furnishLot(g,w,d,h,count);const yard=box(g,w+1.5,.04,3.2,0,-.005,d/2+1.6,'#a69d87');yard.material=surface('earth','#a69d87');const drive=box(g,2.6,.03,3.2,0,.012,d/2+1.6,'#989789');drive.material=surface('stone','#989789');batchStatic(g);g.position.set(q.x,0,q.z);g.rotation.y=yaw;this.scene.add(g);this.solids.push(g);
    const collider=this.world.createCollider(R.ColliderDesc.cuboid(w/2,h/2,d/2).setTranslation(q.x,h/2,q.z).setRotation({x:0,y:Math.sin(yaw/2),z:0,w:Math.cos(yaw/2)}));const bounds=[collider,...lotColliders.map(c=>this.world.createCollider(R.ColliderDesc.cuboid(c.w/2,c.h/2,c.d/2).setTranslation(q.x+Math.cos(yaw)*c.x+Math.sin(yaw)*c.z,c.y,q.z-Math.sin(yaw)*c.x+Math.cos(yaw)*c.z).setRotation({x:0,y:Math.sin(yaw/2),z:0,w:Math.cos(yaw/2)})))];this.chunks.push({group:g,center:q,colliders:bounds});used.push(q);
    if(count%2===0){const tr=tree(false,count%4);tr.position.set(q.x+nx*side*5,0,q.z+nz*side*5);this.scene.add(tr)}count++;
   }
  }
 }
 createPOIs(){
  const entry=gate();this.scene.add(entry);this.solids.push(entry);for(const z of [-4.4,4.4])this.world.createCollider(R.ColliderDesc.cuboid(.52,2.85,.52).setTranslation(0,2.85,z));this.world.createCollider(R.ColliderDesc.cuboid(.6,.65,5.2).setTranslation(0,5.8,0));
  const sp=places.find(p=>p.id==='shop')!;const sr=nearestRoad(sp,this.roads);this.shop=house(10,8,5,'#ede1b6',true);this.shop.position.set(sr.x+11,0,sr.z);garden(this.shop,10,8,3);this.shop.rotation.y=-Math.PI/2;this.scene.add(this.shop);this.solids.push(this.shop);this.world.createCollider(R.ColliderDesc.cuboid(4,2.5,5).setTranslation(sr.x+11,2.5,sr.z));
  this.bay=person('#64796c',true);this.bay.position.set(-8,0,-2.4);this.bay.rotation.y=2.3;this.scene.add(this.bay);
  const speech=new T.Sprite(new T.SpriteMaterial({map:label('!').map,depthTest:false}));speech.scale.set(.5,.5,1);speech.position.y=2.4;this.bay.add(speech);
  const merchant=person('#ab785e');merchant.position.set(sr.x+5.8,0,sr.z);merchant.rotation.y=-Math.PI/2;this.scene.add(merchant);this.npcs.push({id:'merchant',mesh:merchant,origin:{x:merchant.position.x,z:merchant.position.z}});
  for(let i=0;i<8;i++){const q=places[2+i%5],p=nearestRoad(q,this.roads),n=person(['#a78e67','#68878a','#885d55'][i%3],i%3===0);n.position.set(p.x+(i%2?2:-2),0,p.z+i*3);this.scene.add(n);this.npcs.push({id:'resident-'+i,mesh:n,origin:{x:n.position.x,z:n.position.z}});}
  const cp=places[1];for(let i=-8;i<12;i++){const z=cp.z+i*5;box(this.scene,.25,.8,4.9,cp.x+8,.4,z,'#cec7b0');cyl(this.scene,.07,.07,1.1,cp.x+8,1.1,z,'#b8b29c');const rail=cyl(this.scene,.055,.055,5,cp.x+8,1.55,z,'#b8b29c');rail.rotation.x=Math.PI/2;if(i%3===0){box(this.scene,1.3,.14,1.8,cp.x+5,.55,z,'#9eaa9c');box(this.scene,.12,.52,1.5,cp.x+4.55,.26,z,'#8d9889');const tr=tree(true);tr.position.set(cp.x-12,0,z);this.scene.add(tr);}}
  this.marker=new T.Group();const diamond=new T.Mesh(new T.OctahedronGeometry(.4),new T.MeshBasicMaterial({color:'#f3c65b'}));this.marker.add(diamond);const ring=new T.Mesh(new T.RingGeometry(1.3,1.45,32),new T.MeshBasicMaterial({color:'#f3c65b',side:T.DoubleSide,transparent:true,opacity:.6}));ring.rotation.x=-Math.PI/2;ring.position.y=-3;this.marker.add(ring);this.scene.add(this.marker);
 }
 createAnimals(){
  // Ambient animals in yards and the gate verge; no road traffic or gameplay rewards.
  const gateDog=animal('dog');gateDog.position.set(-9,0,-5);this.scene.add(gateDog);this.animals.push({mesh:gateDog,origin:{x:-9,z:-5},phase:0,kind:'dog'});
  for(let i=0;i<this.chunks.length;i+=12){const lot=this.chunks[i],kind=i%24===0?'dog':'chicken';const anchor=new T.Vector3(0,0,-5.5).applyAxisAngle(new T.Vector3(0,1,0),lot.group.rotation.y).add(lot.group.position);const m=animal(kind);m.position.copy(anchor);this.scene.add(m);this.animals.push({mesh:m,origin:{x:anchor.x,z:anchor.z},phase:i*.7,kind});}
 }
 addVehicle(type:'bike'|'car',name:string,p:Point,angle:number){const mesh=type==='bike'?bike():car();mesh.position.set(p.x,0,p.z);mesh.rotation.y=angle;this.scene.add(mesh);const body=this.world.createRigidBody(R.RigidBodyDesc.kinematicPositionBased().setTranslation(p.x,.65,p.z).setRotation({x:0,y:Math.sin(angle/2),z:0,w:Math.cos(angle/2)}));const collider=this.world.createCollider(R.ColliderDesc.cuboid(type==='bike'?.3:.88,.55,type==='bike'?.86:1.85),body);this.vehicles.push({id:type,name,mesh,body,collider,angle,speed:0,previous:mesh.position.clone(),previousAngle:angle,type});}
 start(continueGame:boolean){if(!this.ready)return;let s=newSave();if(continueGame){try{const v=validateSave(JSON.parse(localStorage.getItem('dong-hai-save-v1')||'null'));if(v)s=v;else this.toast('Chưa có bản lưu hợp lệ. Bắt đầu hành trình mới.');}catch{this.toast('Không đọc được bản lưu. Bắt đầu hành trình mới.');}}
  this.save=s;this.position={...s.position};this.angle=s.angle;this.cameraYaw=s.angle;this.driving=null;this.collider.setEnabled(true);this.body.setTranslation({x:s.position.x,y:1,z:s.position.z},true);this.body.setNextKinematicTranslation({x:s.position.x,y:1,z:s.position.z});this.vertical=0;this.velocity.set(0,0);this.visualPrevious.set(s.position.x,.2,s.position.z);this.visualCurrent.copy(this.visualPrevious);this.previousAngle=s.angle;
  for(const v of this.vehicles){const p=s.vehiclePositions[v.id];const defaults=v.type==='bike'?{x:-5,z:2.7,angle:Math.PI/2}:{x:-24,z:3,angle:Math.PI/2};const q=p&&Number.isFinite(p.x)&&Number.isFinite(p.z)&&Number.isFinite(p.angle)&&p.x>-300&&p.x<1500&&Math.abs(p.z)<650?p:defaults;v.angle=q.angle;v.speed=0;v.body.setTranslation({x:q.x,y:.65,z:q.z},true);v.body.setNextKinematicTranslation({x:q.x,y:.65,z:q.z});v.body.setRotation({x:0,y:Math.sin(q.angle/2),z:0,w:Math.cos(q.angle/2)},true);v.mesh.position.set(q.x,0,q.z);v.mesh.rotation.y=q.angle;v.mesh.userData.reset?.();}
  this.lastChunk='';this.targetId=null;this.route=[];this.routeUpdated=0;this.saved=false;this.paused=false;this.keys.clear();this.camera.position.set(s.position.x-Math.sin(s.angle)*7,4,s.position.z-Math.cos(s.angle)*7);this.toast('Chào mừng về Đông Hải. Chú Bảy đang đợi bạn.');this.persist();this.emit();
 }
 setPaused(p:boolean){this.paused=p;this.velocity.set(0,0);this.visualPrevious.copy(this.visualCurrent);this.keys.clear();this.stick={x:0,y:0};this.audio?.setPaused(p);}
 keydown=(e:KeyboardEvent)=>{if(['INPUT','TEXTAREA'].includes((e.target as HTMLElement)?.tagName))return;const k=e.key.toLowerCase();if(this.qaShot){if(k==='p')this.capture();return;}if(['w','a','s','d',' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k)&&!this.paused)e.preventDefault();if(e.repeat)return;if(k==='escape'){if(!this.paused)this.onPanel('pause');return;}if(this.paused)return;if(k==='m'){this.onPanel('map');return;}if(k==='i'){this.onPanel('inventory');return;}if(k==='e'){this.interact();return;}if(k==='f'){this.toggleVehicle();return;}if(k==='p'){this.capture();return;}this.keys.add(k);};
 keyup=(e:KeyboardEvent)=>this.keys.delete(e.key.toLowerCase());blur=()=>{this.keys.clear();this.stick={x:0,y:0};this.drag=null;};visibility=()=>{this.blur();this.audio.setHidden(document.hidden);if(document.hidden){this.persist();this.last=0;}};context=(e:Event)=>e.preventDefault();
 pointerDown=(e:PointerEvent)=>{if(this.paused||this.qaShot)return;this.drag={id:e.pointerId,x:e.clientX,y:e.clientY};this.renderer.domElement.setPointerCapture(e.pointerId);};
 pointerMove=(e:PointerEvent)=>{if(!this.drag||this.drag.id!==e.pointerId||this.paused)return;this.cameraYaw-=(e.clientX-this.drag.x)*.005;this.pitch=Math.max(-.05,Math.min(.95,this.pitch+(e.clientY-this.drag.y)*.004));this.drag={id:e.pointerId,x:e.clientX,y:e.clientY};};pointerUp=()=>{this.drag=null;};
 press(k:string,down:boolean){if(down)this.keys.add(k);else this.keys.delete(k);}
 toggleVehicle(){if(this.paused||this.qaShot)return;if(this.driving){if(Math.abs(this.driving.speed)>1.8){this.toast('Dừng xe để xuống an toàn.');return;}const v=this.driving;const candidates=[-1,1].map(s=>({x:v.mesh.position.x+Math.cos(v.angle)*s*2,z:v.mesh.position.z-Math.sin(v.angle)*s*2}));let chosen:Point|null=null;for(const p of candidates){const hit=this.world.intersectionWithShape({x:p.x,y:.85,z:p.z},{x:0,y:0,z:0,w:1},new R.Capsule(.52,.26),undefined,undefined,this.collider);if(!hit){chosen=p;break;}}if(!chosen){this.toast('Không có khoảng trống bên cạnh xe. Hãy đỗ chỗ khác.');return;}this.driving=null;this.velocity.set(0,0);this.position=chosen;this.collider.setEnabled(true);this.body.setTranslation({x:chosen.x,y:1,z:chosen.z},true);this.body.setNextKinematicTranslation({x:chosen.x,y:1,z:chosen.z});this.vertical=0;this.audio?.cue('dismount');this.toast('Đã xuống xe.');this.persist();return;}
  const v=this.vehicles.find(v=>distance(this.position,v.mesh.position)<3.3);if(!v){this.toast('Đến gần xe máy hoặc ô tô rồi nhấn F.');return;}this.driving=v;this.velocity.set(0,0);this.collider.setEnabled(false);this.angle=v.angle;this.cameraYaw=v.angle;this.save=advanceMission(this.save,{type:'ENTER_VEHICLE',target:v.id});this.audio?.cue('mount');this.toast('W / S ga & phanh · A / D lái · F xuống xe');this.persist();
 }
 interact(){if(this.paused||this.qaShot)return;this.updateNear();if(this.driving){this.toast('Dừng và xuống xe để tương tác.');return;}if(this.near==='bay'){this.audio?.cue('interact');this.onPanel('dialogue');}else if(this.near==='shop'){this.audio?.cue('interact');this.onPanel('shop');}else if(this.near?.startsWith('resident')){this.toast('Người dân: “Chào cháu! Ra biển buổi chiều mát lắm.”');}else this.toast('Đến gần Chú Bảy hoặc cửa hàng để tương tác.');}
 talk(){this.updateNear();if(this.driving||this.near!=='bay')return;if(this.save.stage===0){this.save=advanceMission(this.save,{type:'TALK',target:'bay'});this.toast('Đã nhận nhiệm vụ. Mua phụ tùng rồi mang ra bờ biển.');}else if(this.save.stage===3){const prev=this.save;this.save=advanceMission(this.save,{type:'DELIVER',target:'bay'});if(prev!==this.save)this.audio?.cue('quest');this.toast(prev===this.save?'Bạn chưa có phụ tùng thuyền.':'HOÀN THÀNH · +250.000 ₫ · +150 XP');}else if(this.save.stage===4)this.toast('Chú Bảy: “Cảm ơn cháu! Thuyền lại ra khơi được rồi.”');else this.toast('Chú Bảy: “Cháu ghé cửa hàng lấy phụ tùng giúp chú nhé.”');this.persist();this.emit();}
 buy(id:string){this.updateNear();if(this.driving||this.near!=='shop')return;const prev=this.save;this.save=purchase(this.save,id);if(prev!==this.save)this.audio?.cue('purchase');this.toast(prev===this.save?'Bạn chưa đủ tiền.':'Đã thêm vật phẩm vào túi đồ.');this.persist();this.emit();}
 waypoint(id:string|null){this.targetId=id;this.routeUpdated=0;this.emit();}
 resetPosition(){if(this.qaShot)return;const p=nearestRoad({x:-12,z:0},this.roads);if(this.driving){this.driving.speed=0;this.driving.body.setTranslation({x:p.x,y:.65,z:p.z},true);this.driving.body.setNextKinematicTranslation({x:p.x,y:.65,z:p.z});}else{this.body.setTranslation({x:p.x,y:1,z:p.z},true);this.body.setNextKinematicTranslation({x:p.x,y:1,z:p.z});}this.position=p;this.vertical=0;this.toast('Đã trở về khu vực cổng.');this.persist();}
 changeQuality(q:string){this.quality=q;this.lastChunk='';this.renderer.setPixelRatio(q==='low'?1:Math.min(devicePixelRatio,q==='high'?2:1.5));this.renderer.shadowMap.enabled=q!=='low';this.resize();}
 changeTime(golden:boolean){this.sky.material.uniforms.sunPosition.value.set(-.6,golden?.2:.62,.65);this.sun.color.set(golden?'#ffb673':'#fff1c9');this.sun.intensity=golden?2.7:3;this.scene.background=new T.Color(golden?'#c6b49b':'#9ac7d5');this.scene.fog=new T.FogExp2(golden?'#c2b6a2':'#a6c6c4',.0013);this.sunAngle=golden?1:0;}
 sound(enabled:boolean){this.audio.configure({enabled});if(enabled)void this.audio.unlock().then(ok=>{if(!ok||this.audio.error)this.toast(this.audio.error||'Bấm bật âm thanh để thử lại.')});}
 setAudio(patch:Partial<AudioSettings>){this.audio.configure(patch);}
 unlockAudio(){if(!this.qaMode)void this.audio.unlock().then(()=>{if(this.audio.error)this.toast(this.audio.error)});}
 persist=()=>{if(!this.ready||this.qaMode)return;this.save={...this.save,position:{...this.position},angle:this.angle,vehiclePositions:Object.fromEntries(this.vehicles.map(v=>[v.id,{x:v.body.translation().x,z:v.body.translation().z,angle:v.angle}]))};try{localStorage.setItem('dong-hai-save-v1',JSON.stringify(this.save));this.saved=true;}catch{this.saved=false;this.toast('Không lưu được trên trình duyệt này.');}};
 updateNear(){const s=places.find(p=>p.id==='shop')!,sp=nearestRoad(s,this.roads);this.near=null;if(distance(this.position,this.bay.position)<3.4)this.near='bay';else if(distance(this.position,{x:sp.x+5,z:sp.z})<5)this.near='shop';else{const n=this.npcs.find(n=>distance(this.position,n.mesh.position)<2.5);if(n)this.near=n.id;} }
 tick(dt:number,time:number){if(this.paused||this.qaShot)return;this.visualPrevious.copy(this.visualCurrent);this.previousAngle=this.angle;for(const v of this.vehicles){const p=v.body.translation();v.previous.set(p.x,p.y-.6,p.z);v.previousAngle=v.angle;}
  const f=(this.keys.has('w')||this.keys.has('arrowup')?1:0)-(this.keys.has('s')||this.keys.has('arrowdown')?1:0)-this.stick.y;
  const side=(this.keys.has('d')||this.keys.has('arrowright')?1:0)-(this.keys.has('a')||this.keys.has('arrowleft')?1:0)+this.stick.x;
  if(this.driving){const v=this.driving;v.speed+=f*(v.type==='bike'?8:6)*dt;v.speed*=Math.exp(-dt*(this.keys.has(' ')?6:Math.abs(f)<.05?1.3:.13));v.speed=Math.max(-5,Math.min(v.type==='bike'?22:27,v.speed));v.angle-=side*dt*1.5*Math.min(Math.abs(v.speed)/4,1)*Math.sign(v.speed||1);const dx=Math.sin(v.angle)*v.speed*dt,dz=Math.cos(v.angle)*v.speed*dt;this.vcontroller.computeColliderMovement(v.collider,{x:dx,y:-.1,z:dz});const move=this.vcontroller.computedMovement();if(Math.hypot(move.x,move.z)<Math.hypot(dx,dz)*.5)v.speed*=.7;const p=v.body.translation();v.body.setNextKinematicTranslation({x:Math.max(-180,Math.min(1518,p.x+move.x)),y:Math.max(.6,p.y+move.y),z:Math.max(-590,Math.min(190,p.z+move.z))});v.body.setNextKinematicRotation({x:0,y:Math.sin(v.angle/2),z:0,w:Math.cos(v.angle/2)});this.angle=v.angle;if(!this.drag)this.cameraYaw+=Math.atan2(Math.sin(v.angle-this.cameraYaw),Math.cos(v.angle-this.cameraYaw))*dt*1.8;
  }else{const n=Math.max(1,Math.hypot(f,side));const speed=this.keys.has('shift')?6:3.2;const targetX=(Math.sin(this.cameraYaw)*f-Math.cos(this.cameraYaw)*side)/n*speed,targetZ=(Math.cos(this.cameraYaw)*f+Math.sin(this.cameraYaw)*side)/n*speed;const rate=Math.hypot(f,side)>.05?10:16;this.velocity.set(damp(this.velocity.x,targetX,rate,dt),damp(this.velocity.y,targetZ,rate,dt));const dx=this.velocity.x,dz=this.velocity.y;if(Math.hypot(dx,dz)>.15)this.angle=turn(this.angle,Math.atan2(dx,dz),12,dt);if(this.keys.has(' ')&&this.controller.computedGrounded()){this.audio?.cue('jump');this.vertical=6.1;this.keys.delete(' ');}this.vertical=Math.max(-20,this.vertical-18*dt);this.controller.computeColliderMovement(this.collider,{x:dx*dt,y:this.vertical*dt,z:dz*dt});const d=this.controller.computedMovement(),p=this.body.translation();if(this.controller.computedGrounded()&&this.vertical<0)this.vertical=0;this.body.setNextKinematicTranslation({x:Math.max(-180,Math.min(1518,p.x+d.x)),y:p.y+d.y,z:Math.max(-590,Math.min(190,p.z+d.z))});}
  this.world.step();for(const v of this.vehicles){const p=v.body.translation();v.mesh.position.set(p.x,p.y-.6,p.z);v.mesh.rotation.y=v.angle;v.mesh.userData.update?.(dt,v.speed,this.driving===v?-side:0);}
  const p=this.driving?this.driving.body.translation():this.body.translation();this.position={x:p.x,z:p.z};this.visualCurrent.set(p.x,this.driving?(this.driving.type==='bike'?-.02:.23):p.y-.8,p.z);if(this.visualCurrent.distanceTo(this.visualPrevious)>3)this.visualPrevious.copy(this.visualCurrent);this.motionSpeed=Math.hypot(this.visualCurrent.x-this.visualPrevious.x,this.visualCurrent.z-this.visualPrevious.z)/dt;this.airborne=!this.driving&&!this.controller.computedGrounded();this.player.visible=this.driving?.type!=='car';
  const cp=nearestRoad(places[1],this.roads);if(this.save.stage>0)this.bay.position.set(cp.x-2,0,cp.z-3);else this.bay.position.set(-8,0,-2.4);
  for(const n of this.npcs){if(n.id==='merchant'){n.mesh.userData.update?.(dt,0,false,false);continue;}const near=distance(this.position,n.origin)<90;n.mesh.visible=near;if(near){n.mesh.position.z=n.origin.z+Math.sin(time*.17+n.origin.x)*4;n.mesh.rotation.y=Math.cos(time*.17+n.origin.x)>0?0:Math.PI;animatePerson(n.mesh,time,1);}}
  updateAnimals(this.animals||[],this.position,time);this.bay.userData.update?.(dt,0,false,false);
  for(const poi of places)if(distance(this.position,poi)<24&&!this.save.discovered.includes(poi.id)){this.save={...this.save,xp:this.save.xp+20,discovered:[...this.save.discovered,poi.id]};this.toast('KHÁM PHÁ'+' · '+poi.name+' · +20 XP');this.persist();}
  const key=Math.floor(p.x/100)+':'+Math.floor(p.z/100);if(key!==this.lastChunk){this.lastChunk=key;const radius=this.quality==='low'?150:230;for(const c of this.chunks){const d=distance(this.position,c.center);c.group.visible=d<radius;c.colliders.forEach(x=>x.setEnabled(d<100));}}
  this.saveTimer+=dt;if(this.saveTimer>12){this.persist();this.saveTimer=0;}this.audio?.update(dt,{speed:this.driving?.speed??this.motionSpeed,vehicle:this.driving?.type??null,grounded:!this.airborne,coastDistance:distance(this.position,places[1]),surface:()=>distance(this.position,nearestRoad(this.position,this.roads))<3.5?'road':'dirt'});
 }
 loop=(now:number)=>{if(this.disposed)return;const delta=this.last?Math.min((now-this.last)/1000,.08):.016;this.last=now;if(!this.qaShot)this.anim+=delta;if(!document.hidden){this.accumulator=Math.min(this.accumulator+delta,.1);while(this.accumulator>=1/60){this.tick(1/60,this.anim);this.accumulator-=1/60;}
  if(this.ready){const alpha=this.paused?1:this.accumulator/(1/60);for(const v of this.vehicles){const q=v.body.translation();const current=new T.Vector3(q.x,q.y-.6,q.z);if(current.distanceTo(v.previous)>3)v.previous.copy(current);v.mesh.position.lerpVectors(v.previous,current,alpha);v.mesh.rotation.y=v.previousAngle+Math.atan2(Math.sin(v.angle-v.previousAngle),Math.cos(v.angle-v.previousAngle))*alpha;}this.player.position.lerpVectors(this.visualPrevious,this.visualCurrent,alpha);this.player.rotation.z=this.driving?.type==='bike'?this.driving.mesh.rotation.z:0;this.player.rotation.y=this.previousAngle+Math.atan2(Math.sin(this.angle-this.previousAngle),Math.cos(this.angle-this.previousAngle))*alpha;if(!this.paused&&!this.qaShot)this.player.userData.update(delta,this.motionSpeed,!!this.driving,this.airborne);const p=this.player.position;const dist=this.driving?this.driving.type==='car'?9:7:5.5;const target=new T.Vector3(p.x,p.y+1.35,p.z);const desired=new T.Vector3(p.x-Math.sin(this.cameraYaw)*dist*Math.cos(this.pitch),p.y+1.8+dist*Math.sin(this.pitch),p.z-Math.cos(this.cameraYaw)*dist*Math.cos(this.pitch));const dir=desired.clone().sub(target);const ray=new T.Raycaster(target,dir.clone().normalize(),.1,dir.length());const hits=ray.intersectObjects(this.solids.filter(m=>m.visible),true);if(hits.length)desired.copy(target).addScaledVector(dir.normalize(),Math.max(.7,hits[0].distance-.3));this.camera.position.lerp(desired,1-Math.exp(-delta*9));this.camera.lookAt(target);this.sun.position.set(p.x-60,this.sunAngle?55:110,p.z+65);this.sun.target.position.set(p.x,0,p.z);
  const stage=mission.stages[this.save.stage];const poi=places.find(x=>x.id===(this.targetId||stage?.poi));this.marker.visible=!!poi;if(poi){const goal=stage?.poi==='gate'&&!this.targetId?this.bay.position:poi;this.marker.position.set(goal.x,3.5+Math.sin(this.anim*2)*.15,goal.z);this.marker.children[0].rotation.y=this.anim;if(now-this.routeUpdated>2500){this.route=route(this.position,poi,this.roads);this.routeUpdated=now;}}
  if(this.qaShot){const shot=this.qaShot;this.camera.position.set(shot.anchor.x+shot.offset[0],shot.offset[1],shot.anchor.z+shot.offset[2]);this.camera.lookAt(shot.anchor.x,shot.lookHeight,shot.anchor.z);this.sun.position.set(shot.anchor.x-60,110,shot.anchor.z+65);this.sun.target.position.set(shot.anchor.x,0,shot.anchor.z);}this.renderer.render(this.scene,this.camera);this.frames++;if(now-this.lastEmit>150){this.fps=Math.round(this.frames*1000/(now-this.lastEmit||150));this.frames=0;this.lastEmit=now;this.updateNear();this.emit();}}}
  this.raf=requestAnimationFrame(this.loop);
 };
 emit(){const nearVehicle=!this.driving&&this.vehicles.some(v=>distance(this.position,v.mesh.position)<3.3);const prompt=this.driving?'F · Xuống xe':this.near==='bay'?'E · Nói chuyện với Chú Bảy':this.near==='shop'?'E · Vào cửa hàng':this.near?.startsWith('resident')?'E · Chào người dân':nearVehicle?'F · Lên xe':'';const closest=places.reduce((a,b)=>distance(this.position,a)<distance(this.position,b)?a:b);this.onState({save:{...this.save},position:{...this.position},speed:Math.round(Math.abs(this.driving?.speed||0)*3.6),driving:this.driving?.name||null,prompt,near:this.near,location:distance(this.position,closest)<70?closest.name:'Đông Hải · Đường trong làng',fps:this.fps,heading:this.cameraYaw,time:this.sunAngle?'17:15':'09:30',route:this.route,ready:this.ready,saved:this.saved});}
 dispose(){this.disposed=true;cancelAnimationFrame(this.raf);this.resizeObs.disconnect();window.removeEventListener('keydown',this.keydown);window.removeEventListener('keyup',this.keyup);window.removeEventListener('blur',this.blur);document.removeEventListener('visibilitychange',this.visibility);window.removeEventListener('pagehide',this.persist);this.audio?.dispose();this.world?.free();this.player.userData.dispose?.();this.bay?.userData.dispose?.();for(const n of this.npcs)n.mesh.userData.dispose?.();const geometries=new Set<T.BufferGeometry>(),mats=new Set<T.Material>();this.scene.traverse(o=>{if(o instanceof T.Mesh){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>mats.add(m));}});geometries.forEach(g=>g.dispose());mats.forEach(m=>{if('map'in m)(m.map as T.Texture)?.dispose();m.dispose();});this.renderer.dispose();this.renderer.domElement.remove();}
}
