import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import ts from 'typescript';
import R from '@dimforge/rapier3d-compat';
const dir=mkdtempSync(join(tmpdir(),'dong-hai-tests-'));
for(const file of ['content','navigation'])writeFileSync(join(dir,file+'.mjs'),ts.transpileModule(readFileSync(new URL('../game/'+file+'.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
const {newSave,advanceMission,purchase,validateSave,local,places}=await import(join(dir,'content.mjs'));
const {route,nearestOnSegment,distance}=await import(join(dir,'navigation.mjs'));
process.on('exit',()=>rmSync(dir,{recursive:true,force:true}));
test('origin and local axis directions',()=>{assert.deepEqual(local(12.570061,109.222798),{x:0,z:-0});assert.ok(local(12.571061,109.223798).x>0);assert.ok(local(12.571061,109.223798).z<0)});
test('mission finishes once with exact cost, item consumption and reward',()=>{let s=newSave();s=advanceMission(s,{type:'TALK',target:'bay'});s=purchase(s,'engine-part');s=advanceMission(s,{type:'ENTER_VEHICLE',target:'bike'});s=advanceMission(s,{type:'DELIVER',target:'bay'});assert.equal(s.stage,4);assert.equal(s.money,550000);assert.equal(s.xp,150);assert.equal(s.inventory['engine-part'],0);assert.equal(advanceMission(s,{type:'DELIVER',target:'bay'}),s)});
test('pre-purchased quest item never requires a second purchase',()=>{let s=purchase(newSave(),'engine-part');s=advanceMission(s,{type:'TALK',target:'bay'});assert.equal(s.stage,2);assert.equal(s.money,300000)});
test('wrong event/target cannot advance mission',()=>{const s=newSave();assert.equal(advanceMission(s,{type:'DELIVER',target:'bay'}),s);assert.equal(advanceMission(s,{type:'TALK',target:'resident'}),s)});
test('delivery requires an item',()=>{const s={...newSave(),stage:3};assert.equal(advanceMission(s,{type:'DELIVER',target:'bay'}),s)});
test('insufficient funds and invalid item leave state untouched',()=>{const s={...newSave(),money:1};assert.equal(purchase(s,'engine-part'),s);assert.equal(purchase(s,'unknown'),s)});
test('save round-trip retains progress',()=>{const s=purchase(newSave(),'water');assert.deepEqual(validateSave(JSON.parse(JSON.stringify(s))),s)});
test('corrupt save and malformed vehicle positions are rejected/sanitized',()=>{assert.equal(validateSave(null),null);assert.equal(validateSave({...newSave(),inventory:[]}),null);assert.equal(validateSave({...newSave(),money:-1}),null);assert.equal(validateSave({...newSave(),stage:9}),null);assert.deepEqual(validateSave({...newSave(),vehiclePositions:{bike:null,car:{x:Infinity,z:0,angle:0}}}).vehiclePositions,{})});
test('segment projection clamps and handles zero length',()=>{assert.deepEqual(nearestOnSegment({x:20,z:3},{x:0,z:0},{x:10,z:0}),{x:10,z:0});assert.deepEqual(nearestOnSegment({x:20,z:3},{x:0,z:0},{x:0,z:0}),{x:0,z:0})});
test('A* respects direction and disconnected roads',()=>{const r=[{id:'r',points:[{x:0,z:0},{x:10,z:0}],oneway:true}];assert.equal(route({x:0,z:0},{x:10,z:0},r).length,4);assert.deepEqual(route({x:10,z:0},{x:0,z:0},r),[]);assert.deepEqual(route({x:0,z:0},{x:10,z:0},[]),[])});
test('OSM route links gate, shop and coast',()=>{const roads=JSON.parse(readFileSync(new URL('../public/data/roads.json',import.meta.url)));for(const id of ['shop','coast']){const path=route(places[0],places.find(p=>p.id===id),roads);assert.ok(path.length>3,id+' disconnected');assert.ok(path.slice(1,-1).reduce((s,p,i,a)=>s+(i?distance(p,a[i-1]):0),0)>100)}});
await R.init();
test('Rapier capsule stays above ground and cannot cross a wall after 600 steps',()=>{const world=new R.World({x:0,y:-18,z:0});try{world.timestep=1/60;world.createCollider(R.ColliderDesc.cuboid(30,.3,30).setTranslation(0,-.35,0));world.createCollider(R.ColliderDesc.cuboid(.5,3,5).setTranslation(3,3,0));const body=world.createRigidBody(R.RigidBodyDesc.kinematicPositionBased().setTranslation(0,1,0));const collider=world.createCollider(R.ColliderDesc.capsule(.52,.26),body);const controller=world.createCharacterController(.025);controller.enableSnapToGround(.3);world.step();for(let i=0;i<600;i++){controller.computeColliderMovement(collider,{x:.06,y:-.05,z:0});const m=controller.computedMovement(),p=body.translation();body.setNextKinematicTranslation({x:p.x+m.x,y:p.y+m.y,z:p.z+m.z});world.step()}const p=body.translation();assert.ok(p.x<2.3&&p.x>1.5,JSON.stringify(p));assert.ok(p.y>.7&&p.y<.9,JSON.stringify(p))}finally{world.free()}});
