'use client';
import {useEffect,useRef,useState} from 'react';
import {GameAudio,type SoundCue} from '@/game/audio';
export default function AudioCheck(){
 const audio=useRef<GameAudio|null>(null),[status,setStatus]=useState('Chưa bật'),[mode,setMode]=useState('walk'),[result,setResult]=useState(''),[paused,setPaused]=useState(false);
 useEffect(()=>{const a=new GameAudio(false);a.configure({enabled:true,master:.7,music:.3,ambience:.5,effects:.8});audio.current=a;const visibility=()=>a.setHidden(document.hidden);document.addEventListener('visibilitychange',visibility);const poll=setInterval(()=>{const s=a.status();setStatus(`${s.context} · ${s.loaded}/${s.total} âm thanh · ${s.loops} vòng lặp · RMS ${s.signalRms.toFixed(5)} · engine ${s.engineGain.toFixed(4)} · ${s.settings.enabled?'bật':'tắt'} · ${s.paused?'paused':'active'} · cues: ${s.recent.join(', ')}${s.error?' · '+s.error:''}`)},200);return()=>{clearInterval(poll);document.removeEventListener('visibilitychange',visibility);a.dispose();audio.current=null}},[]);
 useEffect(()=>{const timer=setInterval(()=>audio.current?.update(.05,{speed:mode==='idle'?0:mode==='walk'?3:mode==='run'?6:12,vehicle:mode==='bike'?'bike':mode==='car'?'car':null,grounded:true,coastDistance:mode==='coast'?0:400,surface:()=>mode==='dirt'?'dirt':'road'}),50);return()=>clearInterval(timer)},[mode]);
 const cue=(id:SoundCue)=>{audio.current?.cue(id);setResult('Đã phát '+id)};
 return <main style={{padding:'40px',maxWidth:900,margin:'auto',color:'#e5eee8',background:'#193a38',minHeight:'100vh',fontFamily:'sans-serif'}}><h1 style={{fontSize:28}}>Kiểm tra âm thanh Đông Hải</h1><p>Trang kiểm tra dev độc lập với WebGL. Bấm bật âm thanh trước khi thử.</p><button className="gold-button" onClick={()=>void audio.current?.unlock()}>Bật âm thanh kiểm tra</button><p role="status">{status}</p><div style={{display:'flex',flexWrap:'wrap',gap:12,marginBlock:20}}>{[['idle','Đứng yên'],['walk','Đi trên đường'],['dirt','Đi trên đất'],['run','Chạy'],['bike','Xe máy'],['car','Ô tô'],['coast','Gần biển']].map(([id,label])=><button className="quiet-button" key={id} aria-pressed={mode===id} onClick={()=>setMode(id)}>{label}</button>)}</div><p>Chế độ: {mode}</p><div style={{display:'flex',flexWrap:'wrap',gap:12}}>{(['jump','land','mount','dismount','interact','purchase','quest','ui'] as SoundCue[]).map(id=><button className="quiet-button" key={id} onClick={()=>cue(id)}>{id}</button>)}</div><p>{result}</p><button className="quiet-button" onClick={()=>{setPaused(!paused);audio.current?.setPaused(!paused)}}>{paused?'Tiếp tục mô phỏng':'Tạm dừng mô phỏng'}</button><button className="quiet-button" onClick={()=>{audio.current?.configure({enabled:!audio.current.settings.enabled});setResult(audio.current?.settings.enabled?'Âm thanh bật':'Âm thanh tắt')}}>Bật/tắt toàn bộ</button><p>Nhạc giảm khi tạm dừng; bước chân và động cơ ngừng. Chuyển tab để kiểm tra việc tạm ngừng âm thanh nền.</p><a href="/">Về game</a></main>
}
